<a href="https://colab.research.google.com/github/aerraezs/AO_VIU/blob/main/02_AO_03MIAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="#002856"><h1 align="left">Algoritmos de optimización</h1></font>
<font color="#002856"><h2 align="left">VC-2 Diseño de algoritmos</h2></font>

#### Profesor: Juan Francisco Vallalta Rueda
---

# Medir el tiempo de ejecución

Medir el tiempo de ejecución de un programa es una tarea muy importante, ya que programar no sólo consiste en crear código que funcione, sino código que pueda ser ejecutado en un tiempo razonable.

La librería **time** nos permite medir el tiempo de ejecución en Python, utilizando el método  `time()`.

In [ ]:
# Medida del tiempo de ejecucion con time
import time
inicio = time.time()

# Código a medir
time.sleep(10)
# -------------

fin = time.time()
print(fin-inicio) # 1.0005340576171875

10.002641201019287


# Generación de números enteros aleatorios

In [ ]:
# Mödulo random
import random

# Inicialización del rango de números a generar
inicio= 0
fin = 1000
cantidad = 100

# Lista de números aleatorios
numeros_aleatorios = [random.randint(inicio,fin) for i in range(cantidad)]
print(numeros_aleatorios)

[695, 385, 928, 730, 82, 906, 416, 429, 707, 59, 556, 643, 489, 851, 385, 940, 465, 515, 942, 745, 219, 305, 8, 943, 218, 371, 483, 174, 136, 257, 482, 94, 385, 201, 530, 522, 460, 204, 882, 754, 24, 341, 576, 946, 97, 758, 491, 270, 746, 12, 652, 158, 483, 623, 710, 665, 856, 935, 963, 342, 247, 890, 673, 143, 54, 905, 868, 522, 1, 248, 690, 720, 363, 878, 567, 586, 593, 901, 574, 835, 853, 915, 188, 937, 489, 182, 228, 948, 247, 291, 223, 602, 741, 761, 199, 691, 72, 718, 965, 583]


# Ejercicios

## Implementa  una solución para el problema del cambio de moneda en un sistema monetario con las siguientes monedas: {1, 2, 5, 10, 20 , 50}

In [ ]:
# Problema de cambio de monedas





# Reto VC-2

## Opción 1: Implementa una solución al problema de las 8 reinas en un tablero 8x8

In [ ]:
# Ocho reinas
# Escribe aquí tu código




## Opción 2: Implementa una solución del problema de las Torres de Hanoi para un número arbitrario n de fichas

In [ ]:
# Torres de Hanoy
# Escribe aquí tu código
import numpy as np

discos = 4
torres = 3

matriz_torres= np.zeros((discos, torres-1))
discos = np.arange(5)[1:].reshape(discos,1)

matriz_h = np.block([discos,matriz_torres])

print(matriz_h)

juego=matriz_h


[[1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]]


In [ ]:
juego[:,0].min()
juego

1.0

In [1]:
def Mover(discos, origen, destino, aux):
    if discos > 0:
        Mover(discos - 1, origen, aux, destino)
        print(f"Mover disco {discos} desde {origen} a {destino}")
        Mover(discos - 1, aux, destino, origen)

Mover(3, "P1", "P2", "P3")

Mover disco 1 desde P1 a P2
Mover disco 2 desde P1 a P3
Mover disco 1 desde P2 a P3
Mover disco 3 desde P1 a P2
Mover disco 1 desde P3 a P1
Mover disco 2 desde P3 a P2
Mover disco 1 desde P1 a P2


In [86]:
# Definir el número de filas y columnas
discos = 4
torres = 3

# Crear una matriz con n filas y m columnas
torres = [[i + 1 if j == 0 else 0 for j in range(torres)] for i in range(discos)]

# Imprimir la matriz
for fila in torres:
    print(fila)

[1, 0, 0]
[2, 0, 0]
[3, 0, 0]
[4, 0, 0]


In [87]:

def imprimir_matriz(matriz):
    for fila in matriz:
        print(fila)
    print("------")

def Mover(discos, origen, destino, aux, torres):
    if discos > 0:
        Mover(discos - 1, origen, aux, destino, torres)

        # Buscar el disco a mover en la columna origen
        disco = 0
        for i in range(len(torres)):
            if torres[i][origen] != 0:
                disco = torres[i][origen]
                torres[i][origen] = 0
                break

        # Encontrar la posición vacía en la columna destino
        indice_destino = len(torres) - 1
        while torres[indice_destino][destino] != 0:
            indice_destino -= 1

        # Mover el disco al destino y rellenar con ceros
        count=0
        torres[indice_destino][destino] = disco
        for i in range(indice_destino - 1, -1, -1):
            count +=1
            torres[i][destino] = 0

        print(f'Paso {count}')
        # Imprimir la matriz después del movimiento
        imprimir_matriz(torres)

        Mover(discos - 1, aux, destino, origen, torres)



# Imprimir la matriz inicial
imprimir_matriz(torres)

# Llamar a la función Mover con la matriz y los parámetros dados
Mover(4, 0, 2, 1, torres)




[1, 0, 0]
[2, 0, 0]
[3, 0, 0]
[4, 0, 0]
------
Paso 3
[0, 0, 0]
[2, 0, 0]
[3, 0, 0]
[4, 1, 0]
------
Paso 3
[0, 0, 0]
[0, 0, 0]
[3, 0, 0]
[4, 1, 2]
------
Paso 2
[0, 0, 0]
[0, 0, 0]
[3, 0, 1]
[4, 0, 2]
------
Paso 3
[0, 0, 0]
[0, 0, 0]
[0, 0, 1]
[4, 3, 2]
------
Paso 2
[0, 0, 0]
[0, 0, 0]
[1, 0, 0]
[4, 3, 2]
------
Paso 2
[0, 0, 0]
[0, 0, 0]
[1, 2, 0]
[4, 3, 0]
------
Paso 1
[0, 0, 0]
[0, 1, 0]
[0, 2, 0]
[4, 3, 0]
------
Paso 3
[0, 0, 0]
[0, 1, 0]
[0, 2, 0]
[0, 3, 4]
------
Paso 2
[0, 0, 0]
[0, 0, 0]
[0, 2, 1]
[0, 3, 4]
------
Paso 3
[0, 0, 0]
[0, 0, 0]
[0, 0, 1]
[2, 3, 4]
------
Paso 2
[0, 0, 0]
[0, 0, 0]
[1, 0, 0]
[2, 3, 4]
------
Paso 2
[0, 0, 0]
[0, 0, 0]
[1, 0, 3]
[2, 0, 4]
------
Paso 3
[0, 0, 0]
[0, 0, 0]
[0, 0, 3]
[2, 1, 4]
------
Paso 1
[0, 0, 0]
[0, 0, 2]
[0, 0, 3]
[0, 1, 4]
------
Paso 0
[0, 0, 1]
[0, 0, 2]
[0, 0, 3]
[0, 0, 4]
------
