<a href="https://colab.research.google.com/github/aerraezs/AO_VIU/blob/main/02_AO_03MIAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="#002856"><h1 align="left">Algoritmos de optimización</h1></font>
<font color="#002856"><h2 align="left">VC-2 Diseño de algoritmos</h2></font>

#### Profesor: Juan Francisco Vallalta Rueda
---

# Medir el tiempo de ejecución

Medir el tiempo de ejecución de un programa es una tarea muy importante, ya que programar no sólo consiste en crear código que funcione, sino código que pueda ser ejecutado en un tiempo razonable.

La librería **time** nos permite medir el tiempo de ejecución en Python, utilizando el método  `time()`.

In [ ]:
# Medida del tiempo de ejecucion con time
import time
inicio = time.time()

# Código a medir
time.sleep(10)
# -------------

fin = time.time()
print(fin-inicio) # 1.0005340576171875

10.002641201019287


In [ ]:
#convierte los multiplos de 10 en prefijos
def convertir_prefijo(numero):
    prefijos = {
        '': 1,
        'm': 1e-3,
        'µ': 1e-6,
        'n': 1e-9,
        'p': 1e-12,
    }

    for prefijo, valor in prefijos.items():
        if valor <= abs(numero):
            numero_con_prefijo = numero / valor
            return f'{numero_con_prefijo:.3f} {prefijo}s'

    return f'{numero:.3e} s'


# calculo el tiempo que transcurre el ejercicio
def tiempo(funcion):
  import time
  # Medida del tiempo de ejecucion con time
  inicio = time.time()
  funcion
  fin = time.time()
  tiempo_estimado=fin-inicio
  return convertir_prefijo(round(tiempo_estimado,10))

# Generación de números enteros aleatorios

In [ ]:
# Mödulo random
import random

# Inicialización del rango de números a generar
inicio= 0
fin = 1000
cantidad = 100

# Lista de números aleatorios
numeros_aleatorios = [random.randint(inicio,fin) for i in range(cantidad)]
print(numeros_aleatorios)

[695, 385, 928, 730, 82, 906, 416, 429, 707, 59, 556, 643, 489, 851, 385, 940, 465, 515, 942, 745, 219, 305, 8, 943, 218, 371, 483, 174, 136, 257, 482, 94, 385, 201, 530, 522, 460, 204, 882, 754, 24, 341, 576, 946, 97, 758, 491, 270, 746, 12, 652, 158, 483, 623, 710, 665, 856, 935, 963, 342, 247, 890, 673, 143, 54, 905, 868, 522, 1, 248, 690, 720, 363, 878, 567, 586, 593, 901, 574, 835, 853, 915, 188, 937, 489, 182, 228, 948, 247, 291, 223, 602, 741, 761, 199, 691, 72, 718, 965, 583]


# Ejercicios

## Implementa  una solución para el problema del cambio de moneda en un sistema monetario con las siguientes monedas: {1, 2, 5, 10, 20 , 50}

[2, 3, 4, 5]


In [ ]:
import math
# Problema de cambio de monedas

dinero_entregado = 12

def cambio_de_moneda(dinero):
    monedas = {1, 2, 5, 10, 20 , 50}




si


# Reto VC-2

## Opción 1: Implementa una solución al problema de las 8 reinas en un tablero 8x8

In [9]:
# Ocho reinas
# Escribe aquí tu código
import numpy as np



#CREACION DE TABLERO
tablero_cuadrado = 8
l1 = [0, 1]
l2 = [1, 0]

l1_ampliada = l1 * 4
l2_ampliada = l2 * 4

tablero = []
for x in range(int(tablero_cuadrado/2)):
  tablero.append(l1_ampliada)
  tablero.append(l2_ampliada)
tablero = np.array(tablero)

print(tablero)

# EMPIEZA EL JUEGO DE DAMAS
reinas = 8


for x in range(reinas):
  if tablero[0].sum() == 4:
    tablero[0][1] = 2



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [36]:
juego_ajedrez = np.zeros((8,8))
reinas = 8


for x in range(reinas):
  if juego_ajedrez[x].sum(axis=0) == 0:
    juego_ajedrez[x] = 2

print(juego_ajedrez)



[[2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]]


## Opción 2: Implementa una solución del problema de las Torres de Hanoi para un número arbitrario n de fichas

In [ ]:
# Parametros de entrada
discos = 4


# Creacion de la matriz juego , las torres son las columnas y los discos son los numeros.
torres = 3
juego = [[i + 1 if j == 0 else 0    for j in range(torres)]    for i in range(discos)    ]

# Visualizacion de las torres de Hanoi
def imprimir_matriz(matriz):
    print("------")
    imprimir_matriz.count += 1
    for fila in matriz:
        print(fila)

#Contador de movimientos
imprimir_matriz.count = 1

#Funcion de movimientos
def Mover(discos, origen, destino, aux, juego):

    if discos > 0:

        Mover(discos - 1, origen, aux, destino, juego)

        # Buscar disco que se puede mover
        disco = 0
        for i in range(len(juego)):
            if juego[i][origen] != 0:
                disco = juego[i][origen]
                juego[i][origen] = 0
                break

        # Buscador de posición en columna destino
        indice_destino = len(juego) - 1
        while juego[indice_destino][destino] != 0:
            indice_destino -= 1

        # Maniobra de moviento de ficha
        juego[indice_destino][destino] = disco
        for i in range(indice_destino - 1, -1, -1):
            juego[i][destino] = 0

        #Presentacion
        print(f'Paso {imprimir_matriz.count-1} ')
        imprimir_matriz(juego)
        print(f"Movimiento del {discos} desde la torre {origen+1} a {destino+1}")
        print("------")

        Mover(discos - 1, aux, destino, origen, juego)


imprimir_matriz(juego)
print("------")

RESULTADO = Mover(discos, 0, 2, 1, juego)

TIEMPO =tiempo(RESULTADO)


print(f'Se realizaron {imprimir_matriz.count-2} movimientos en un tiempo de {TIEMPO}')

------
[1, 0, 0]
[2, 0, 0]
[3, 0, 0]
[4, 0, 0]
------
Paso 1 
------
[0, 0, 0]
[2, 0, 0]
[3, 0, 0]
[4, 1, 0]
Movimiento del 1 desde la torre 1 a 2
------
Paso 2 
------
[0, 0, 0]
[0, 0, 0]
[3, 0, 0]
[4, 1, 2]
Movimiento del 2 desde la torre 1 a 3
------
Paso 3 
------
[0, 0, 0]
[0, 0, 0]
[3, 0, 1]
[4, 0, 2]
Movimiento del 1 desde la torre 2 a 3
------
Paso 4 
------
[0, 0, 0]
[0, 0, 0]
[0, 0, 1]
[4, 3, 2]
Movimiento del 3 desde la torre 1 a 2
------
Paso 5 
------
[0, 0, 0]
[0, 0, 0]
[1, 0, 0]
[4, 3, 2]
Movimiento del 1 desde la torre 3 a 1
------
Paso 6 
------
[0, 0, 0]
[0, 0, 0]
[1, 2, 0]
[4, 3, 0]
Movimiento del 2 desde la torre 3 a 2
------
Paso 7 
------
[0, 0, 0]
[0, 1, 0]
[0, 2, 0]
[4, 3, 0]
Movimiento del 1 desde la torre 1 a 2
------
Paso 8 
------
[0, 0, 0]
[0, 1, 0]
[0, 2, 0]
[0, 3, 4]
Movimiento del 4 desde la torre 1 a 3
------
Paso 9 
------
[0, 0, 0]
[0, 0, 0]
[0, 2, 1]
[0, 3, 4]
Movimiento del 1 desde la torre 2 a 3
------
Paso 10 
------
[0, 0, 0]
[0, 0, 0]
[0, 0, 1]
